"""Constants specific to the Space Combat game."""

from shared.constants import BLACK, WHITE, RED, YELLOW, CYAN

# Window settings
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Game settings
FPS = 60
PLAYER_SPEED = 5
BULLET_SPEED = 7
ENEMY_SPEED = 2
ENEMY_SPAWN_RATE = 60  # frames between enemy spawns

# Entity sizes
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 30
BULLET_WIDTH = 4
BULLET_HEIGHT = 10
ENEMY_WIDTH = 30
ENEMY_HEIGHT = 20

# Colors
BACKGROUND_COLOR = BLACK
PLAYER_COLOR = CYAN
PLAYER_OUTLINE_COLOR = (180, 255, 255)
PLAYER2_COLOR = (50, 220, 80)
PLAYER2_OUTLINE_COLOR = (180, 255, 180)
BULLET_COLOR = YELLOW
PLAYER2_BULLET_COLOR = (100, 255, 100)
ENEMY_COLOR = RED
TEXT_COLOR = WHITE
EXPLOSION_COLOR = RED

# Scoring
ENEMY_KILL_POINTS = 10
